// Licensed GNU LGPL v3 or later: http://www.gnu.org/licenses/lgpl.html -*-mode:c++;-*-

namespace Rapicorn {

/// A sequence of strings (in C++ of std::string).
sequence StringSeq { string strings; };

/// A sequence of @a any objects, useful when the sequence element types need to be determined at runtime.
sequence AnySeq { any vany; };

/// A sequence of AnySeq sequence objects, useful when multiple AnySeq instances are needed.
sequence AnySeqSeq { AnySeq seq; };

/// A sequence of ARGB pixel values.
sequence PixelSeq { int argb; };

/// Pixbuf - A simple pixel buffer, see Pixmap and PixmapT<> for convenient pixel based image manipulation.
record Pixbuf {
  int       row_length;         ///< Length of a Pixbuf row in pixels.
  PixelSeq  pixels;             ///< Pixel values in 32Bit ARGB format.
  StringSeq variables;
};

} // Rapicorn
