// Licensed GNU LGPL v3 or later: http://www.gnu.org/licenses/lgpl.html
/**
 * @file
 * @brief Aida builtin type definitions.
 */

namespace Aida {
  namespace __system_typedefs__ {
    // special namespace, containing definitions for the builtin TypeMap
    typedef bool	__builtin__bool;
    typedef int32 	__builtin__int32;
    typedef float64	__builtin__float64;
    typedef String  	__builtin__String;
    typedef Any    	__builtin__Any;
  }
}
