// Licensed GNU LGPL v3 or later: http://www.gnu.org/licenses/lgpl.html
/**
 * @file
 * @brief Aida builtin type definitions.
 */

namespace Aida {
  namespace __system_typedefs__ {
    // special namespace, containing definitions for the builtin TypeMap
    typedef string __builtin__string;
    typedef int    __builtin__int;
    typedef float  __builtin__float;
    typedef any    __builtin__any;
  }
}
