/* birnetsignal.inc - preprocessor argument repeater	-*-mode: c++;-*-
 * Copyright (C) 2005 Tim Janik
 *
 * This software is provided "as is"; redistribution and modification
 * is permitted, provided that the following disclaimer is retained.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * In no event shall the authors or contributors be liable for any
 * direct, indirect, incidental, special, exemplary, or consequential
 * damages (including, but not limited to, procurement of substitute
 * goods or services; loss of use, data, or profits; or business
 * interruption) however caused and on any theory of liability, whether
 * in contract, strict liability, or tort (including negligence or
 * otherwise) arising in any way out of the use of this software, even
 * if advised of the possibility of such damage.
 */

/* file contents created with:
   function repeat() {
   echo -ne "#define BIRNET_SIG_$1S "
   i=$2
   n=1
   need_fill=0
   while test $i -gt 0 ; do
   test $need_fill -gt 0 && echo -ne " $3"
   echo -ne " BIRNET_SIG_ARG_$1($n)"
   i=$[$i - 1]
   n=$[$n + 1]
   need_fill=1
   done
   echo
   }
   function undef() {
   echo "#undef BIRNET_SIG_$1S"
   }
   for j in `seq 0 16` ; do z=`printf '%4u' $j`;
   echo "#if   BIRNET_SIG_MATCH ($j)" ;
   echo "#undef BIRNET_SIG_NAME" ; echo "#define BIRNET_SIG_NAME(x) x##$j" ;
   repeat c_TYPENAME $j  ; repeat TYPENAME $j "," ;
   repeat c_TYPE $j      ; repeat TYPE $j "," ;
   repeat c_VAR $j       ; repeat VAR $j "," ;
   repeat c_TYPED_VAR $j ; repeat TYPED_VAR $j "," ;
   echo "#include <rapicorn/birnetsignaldefs.hh>" ;
   undef c_TYPENAME      ; undef TYPENAME
   undef c_TYPE          ; undef TYPE
   undef c_VAR           ; undef VAR
   undef c_TYPED_VAR     ; undef TYPED_VAR
   echo "#endif // $j" ;
   done >xfile
   #
*/


#define BIRNET_SIGNAL_CODE_GENERATION

/* --- generated contents start --- */
#if   BIRNET_SIG_MATCH (0)
#undef BIRNET_SIG_NAME
#define BIRNET_SIG_NAME(x) x##0
#define BIRNET_SIG_c_TYPENAMES 
#define BIRNET_SIG_TYPENAMES 
#define BIRNET_SIG_c_TYPES 
#define BIRNET_SIG_TYPES 
#define BIRNET_SIG_c_VARS 
#define BIRNET_SIG_VARS 
#define BIRNET_SIG_c_TYPED_VARS 
#define BIRNET_SIG_TYPED_VARS 
#include <rapicorn/birnetsignaldefs.hh>
#undef BIRNET_SIG_c_TYPENAMES
#undef BIRNET_SIG_TYPENAMES
#undef BIRNET_SIG_c_TYPES
#undef BIRNET_SIG_TYPES
#undef BIRNET_SIG_c_VARS
#undef BIRNET_SIG_VARS
#undef BIRNET_SIG_c_TYPED_VARS
#undef BIRNET_SIG_TYPED_VARS
#endif // 0
#if   BIRNET_SIG_MATCH (1)
#undef BIRNET_SIG_NAME
#define BIRNET_SIG_NAME(x) x##1
#define BIRNET_SIG_c_TYPENAMES  BIRNET_SIG_ARG_c_TYPENAME(1)
#define BIRNET_SIG_TYPENAMES  BIRNET_SIG_ARG_TYPENAME(1)
#define BIRNET_SIG_c_TYPES  BIRNET_SIG_ARG_c_TYPE(1)
#define BIRNET_SIG_TYPES  BIRNET_SIG_ARG_TYPE(1)
#define BIRNET_SIG_c_VARS  BIRNET_SIG_ARG_c_VAR(1)
#define BIRNET_SIG_VARS  BIRNET_SIG_ARG_VAR(1)
#define BIRNET_SIG_c_TYPED_VARS  BIRNET_SIG_ARG_c_TYPED_VAR(1)
#define BIRNET_SIG_TYPED_VARS  BIRNET_SIG_ARG_TYPED_VAR(1)
#include <rapicorn/birnetsignaldefs.hh>
#undef BIRNET_SIG_c_TYPENAMES
#undef BIRNET_SIG_TYPENAMES
#undef BIRNET_SIG_c_TYPES
#undef BIRNET_SIG_TYPES
#undef BIRNET_SIG_c_VARS
#undef BIRNET_SIG_VARS
#undef BIRNET_SIG_c_TYPED_VARS
#undef BIRNET_SIG_TYPED_VARS
#endif // 1
#if   BIRNET_SIG_MATCH (2)
#undef BIRNET_SIG_NAME
#define BIRNET_SIG_NAME(x) x##2
#define BIRNET_SIG_c_TYPENAMES  BIRNET_SIG_ARG_c_TYPENAME(1)  BIRNET_SIG_ARG_c_TYPENAME(2)
#define BIRNET_SIG_TYPENAMES  BIRNET_SIG_ARG_TYPENAME(1) , BIRNET_SIG_ARG_TYPENAME(2)
#define BIRNET_SIG_c_TYPES  BIRNET_SIG_ARG_c_TYPE(1)  BIRNET_SIG_ARG_c_TYPE(2)
#define BIRNET_SIG_TYPES  BIRNET_SIG_ARG_TYPE(1) , BIRNET_SIG_ARG_TYPE(2)
#define BIRNET_SIG_c_VARS  BIRNET_SIG_ARG_c_VAR(1)  BIRNET_SIG_ARG_c_VAR(2)
#define BIRNET_SIG_VARS  BIRNET_SIG_ARG_VAR(1) , BIRNET_SIG_ARG_VAR(2)
#define BIRNET_SIG_c_TYPED_VARS  BIRNET_SIG_ARG_c_TYPED_VAR(1)  BIRNET_SIG_ARG_c_TYPED_VAR(2)
#define BIRNET_SIG_TYPED_VARS  BIRNET_SIG_ARG_TYPED_VAR(1) , BIRNET_SIG_ARG_TYPED_VAR(2)
#include <rapicorn/birnetsignaldefs.hh>
#undef BIRNET_SIG_c_TYPENAMES
#undef BIRNET_SIG_TYPENAMES
#undef BIRNET_SIG_c_TYPES
#undef BIRNET_SIG_TYPES
#undef BIRNET_SIG_c_VARS
#undef BIRNET_SIG_VARS
#undef BIRNET_SIG_c_TYPED_VARS
#undef BIRNET_SIG_TYPED_VARS
#endif // 2
#if   BIRNET_SIG_MATCH (3)
#undef BIRNET_SIG_NAME
#define BIRNET_SIG_NAME(x) x##3
#define BIRNET_SIG_c_TYPENAMES  BIRNET_SIG_ARG_c_TYPENAME(1)  BIRNET_SIG_ARG_c_TYPENAME(2)  BIRNET_SIG_ARG_c_TYPENAME(3)
#define BIRNET_SIG_TYPENAMES  BIRNET_SIG_ARG_TYPENAME(1) , BIRNET_SIG_ARG_TYPENAME(2) , BIRNET_SIG_ARG_TYPENAME(3)
#define BIRNET_SIG_c_TYPES  BIRNET_SIG_ARG_c_TYPE(1)  BIRNET_SIG_ARG_c_TYPE(2)  BIRNET_SIG_ARG_c_TYPE(3)
#define BIRNET_SIG_TYPES  BIRNET_SIG_ARG_TYPE(1) , BIRNET_SIG_ARG_TYPE(2) , BIRNET_SIG_ARG_TYPE(3)
#define BIRNET_SIG_c_VARS  BIRNET_SIG_ARG_c_VAR(1)  BIRNET_SIG_ARG_c_VAR(2)  BIRNET_SIG_ARG_c_VAR(3)
#define BIRNET_SIG_VARS  BIRNET_SIG_ARG_VAR(1) , BIRNET_SIG_ARG_VAR(2) , BIRNET_SIG_ARG_VAR(3)
#define BIRNET_SIG_c_TYPED_VARS  BIRNET_SIG_ARG_c_TYPED_VAR(1)  BIRNET_SIG_ARG_c_TYPED_VAR(2)  BIRNET_SIG_ARG_c_TYPED_VAR(3)
#define BIRNET_SIG_TYPED_VARS  BIRNET_SIG_ARG_TYPED_VAR(1) , BIRNET_SIG_ARG_TYPED_VAR(2) , BIRNET_SIG_ARG_TYPED_VAR(3)
#include <rapicorn/birnetsignaldefs.hh>
#undef BIRNET_SIG_c_TYPENAMES
#undef BIRNET_SIG_TYPENAMES
#undef BIRNET_SIG_c_TYPES
#undef BIRNET_SIG_TYPES
#undef BIRNET_SIG_c_VARS
#undef BIRNET_SIG_VARS
#undef BIRNET_SIG_c_TYPED_VARS
#undef BIRNET_SIG_TYPED_VARS
#endif // 3
#if   BIRNET_SIG_MATCH (4)
#undef BIRNET_SIG_NAME
#define BIRNET_SIG_NAME(x) x##4
#define BIRNET_SIG_c_TYPENAMES  BIRNET_SIG_ARG_c_TYPENAME(1)  BIRNET_SIG_ARG_c_TYPENAME(2)  BIRNET_SIG_ARG_c_TYPENAME(3)  BIRNET_SIG_ARG_c_TYPENAME(4)
#define BIRNET_SIG_TYPENAMES  BIRNET_SIG_ARG_TYPENAME(1) , BIRNET_SIG_ARG_TYPENAME(2) , BIRNET_SIG_ARG_TYPENAME(3) , BIRNET_SIG_ARG_TYPENAME(4)
#define BIRNET_SIG_c_TYPES  BIRNET_SIG_ARG_c_TYPE(1)  BIRNET_SIG_ARG_c_TYPE(2)  BIRNET_SIG_ARG_c_TYPE(3)  BIRNET_SIG_ARG_c_TYPE(4)
#define BIRNET_SIG_TYPES  BIRNET_SIG_ARG_TYPE(1) , BIRNET_SIG_ARG_TYPE(2) , BIRNET_SIG_ARG_TYPE(3) , BIRNET_SIG_ARG_TYPE(4)
#define BIRNET_SIG_c_VARS  BIRNET_SIG_ARG_c_VAR(1)  BIRNET_SIG_ARG_c_VAR(2)  BIRNET_SIG_ARG_c_VAR(3)  BIRNET_SIG_ARG_c_VAR(4)
#define BIRNET_SIG_VARS  BIRNET_SIG_ARG_VAR(1) , BIRNET_SIG_ARG_VAR(2) , BIRNET_SIG_ARG_VAR(3) , BIRNET_SIG_ARG_VAR(4)
#define BIRNET_SIG_c_TYPED_VARS  BIRNET_SIG_ARG_c_TYPED_VAR(1)  BIRNET_SIG_ARG_c_TYPED_VAR(2)  BIRNET_SIG_ARG_c_TYPED_VAR(3)  BIRNET_SIG_ARG_c_TYPED_VAR(4)
#define BIRNET_SIG_TYPED_VARS  BIRNET_SIG_ARG_TYPED_VAR(1) , BIRNET_SIG_ARG_TYPED_VAR(2) , BIRNET_SIG_ARG_TYPED_VAR(3) , BIRNET_SIG_ARG_TYPED_VAR(4)
#include <rapicorn/birnetsignaldefs.hh>
#undef BIRNET_SIG_c_TYPENAMES
#undef BIRNET_SIG_TYPENAMES
#undef BIRNET_SIG_c_TYPES
#undef BIRNET_SIG_TYPES
#undef BIRNET_SIG_c_VARS
#undef BIRNET_SIG_VARS
#undef BIRNET_SIG_c_TYPED_VARS
#undef BIRNET_SIG_TYPED_VARS
#endif // 4
#if   BIRNET_SIG_MATCH (5)
#undef BIRNET_SIG_NAME
#define BIRNET_SIG_NAME(x) x##5
#define BIRNET_SIG_c_TYPENAMES  BIRNET_SIG_ARG_c_TYPENAME(1)  BIRNET_SIG_ARG_c_TYPENAME(2)  BIRNET_SIG_ARG_c_TYPENAME(3)  BIRNET_SIG_ARG_c_TYPENAME(4)  BIRNET_SIG_ARG_c_TYPENAME(5)
#define BIRNET_SIG_TYPENAMES  BIRNET_SIG_ARG_TYPENAME(1) , BIRNET_SIG_ARG_TYPENAME(2) , BIRNET_SIG_ARG_TYPENAME(3) , BIRNET_SIG_ARG_TYPENAME(4) , BIRNET_SIG_ARG_TYPENAME(5)
#define BIRNET_SIG_c_TYPES  BIRNET_SIG_ARG_c_TYPE(1)  BIRNET_SIG_ARG_c_TYPE(2)  BIRNET_SIG_ARG_c_TYPE(3)  BIRNET_SIG_ARG_c_TYPE(4)  BIRNET_SIG_ARG_c_TYPE(5)
#define BIRNET_SIG_TYPES  BIRNET_SIG_ARG_TYPE(1) , BIRNET_SIG_ARG_TYPE(2) , BIRNET_SIG_ARG_TYPE(3) , BIRNET_SIG_ARG_TYPE(4) , BIRNET_SIG_ARG_TYPE(5)
#define BIRNET_SIG_c_VARS  BIRNET_SIG_ARG_c_VAR(1)  BIRNET_SIG_ARG_c_VAR(2)  BIRNET_SIG_ARG_c_VAR(3)  BIRNET_SIG_ARG_c_VAR(4)  BIRNET_SIG_ARG_c_VAR(5)
#define BIRNET_SIG_VARS  BIRNET_SIG_ARG_VAR(1) , BIRNET_SIG_ARG_VAR(2) , BIRNET_SIG_ARG_VAR(3) , BIRNET_SIG_ARG_VAR(4) , BIRNET_SIG_ARG_VAR(5)
#define BIRNET_SIG_c_TYPED_VARS  BIRNET_SIG_ARG_c_TYPED_VAR(1)  BIRNET_SIG_ARG_c_TYPED_VAR(2)  BIRNET_SIG_ARG_c_TYPED_VAR(3)  BIRNET_SIG_ARG_c_TYPED_VAR(4)  BIRNET_SIG_ARG_c_TYPED_VAR(5)
#define BIRNET_SIG_TYPED_VARS  BIRNET_SIG_ARG_TYPED_VAR(1) , BIRNET_SIG_ARG_TYPED_VAR(2) , BIRNET_SIG_ARG_TYPED_VAR(3) , BIRNET_SIG_ARG_TYPED_VAR(4) , BIRNET_SIG_ARG_TYPED_VAR(5)
#include <rapicorn/birnetsignaldefs.hh>
#undef BIRNET_SIG_c_TYPENAMES
#undef BIRNET_SIG_TYPENAMES
#undef BIRNET_SIG_c_TYPES
#undef BIRNET_SIG_TYPES
#undef BIRNET_SIG_c_VARS
#undef BIRNET_SIG_VARS
#undef BIRNET_SIG_c_TYPED_VARS
#undef BIRNET_SIG_TYPED_VARS
#endif // 5
#if   BIRNET_SIG_MATCH (6)
#undef BIRNET_SIG_NAME
#define BIRNET_SIG_NAME(x) x##6
#define BIRNET_SIG_c_TYPENAMES  BIRNET_SIG_ARG_c_TYPENAME(1)  BIRNET_SIG_ARG_c_TYPENAME(2)  BIRNET_SIG_ARG_c_TYPENAME(3)  BIRNET_SIG_ARG_c_TYPENAME(4)  BIRNET_SIG_ARG_c_TYPENAME(5)  BIRNET_SIG_ARG_c_TYPENAME(6)
#define BIRNET_SIG_TYPENAMES  BIRNET_SIG_ARG_TYPENAME(1) , BIRNET_SIG_ARG_TYPENAME(2) , BIRNET_SIG_ARG_TYPENAME(3) , BIRNET_SIG_ARG_TYPENAME(4) , BIRNET_SIG_ARG_TYPENAME(5) , BIRNET_SIG_ARG_TYPENAME(6)
#define BIRNET_SIG_c_TYPES  BIRNET_SIG_ARG_c_TYPE(1)  BIRNET_SIG_ARG_c_TYPE(2)  BIRNET_SIG_ARG_c_TYPE(3)  BIRNET_SIG_ARG_c_TYPE(4)  BIRNET_SIG_ARG_c_TYPE(5)  BIRNET_SIG_ARG_c_TYPE(6)
#define BIRNET_SIG_TYPES  BIRNET_SIG_ARG_TYPE(1) , BIRNET_SIG_ARG_TYPE(2) , BIRNET_SIG_ARG_TYPE(3) , BIRNET_SIG_ARG_TYPE(4) , BIRNET_SIG_ARG_TYPE(5) , BIRNET_SIG_ARG_TYPE(6)
#define BIRNET_SIG_c_VARS  BIRNET_SIG_ARG_c_VAR(1)  BIRNET_SIG_ARG_c_VAR(2)  BIRNET_SIG_ARG_c_VAR(3)  BIRNET_SIG_ARG_c_VAR(4)  BIRNET_SIG_ARG_c_VAR(5)  BIRNET_SIG_ARG_c_VAR(6)
#define BIRNET_SIG_VARS  BIRNET_SIG_ARG_VAR(1) , BIRNET_SIG_ARG_VAR(2) , BIRNET_SIG_ARG_VAR(3) , BIRNET_SIG_ARG_VAR(4) , BIRNET_SIG_ARG_VAR(5) , BIRNET_SIG_ARG_VAR(6)
#define BIRNET_SIG_c_TYPED_VARS  BIRNET_SIG_ARG_c_TYPED_VAR(1)  BIRNET_SIG_ARG_c_TYPED_VAR(2)  BIRNET_SIG_ARG_c_TYPED_VAR(3)  BIRNET_SIG_ARG_c_TYPED_VAR(4)  BIRNET_SIG_ARG_c_TYPED_VAR(5)  BIRNET_SIG_ARG_c_TYPED_VAR(6)
#define BIRNET_SIG_TYPED_VARS  BIRNET_SIG_ARG_TYPED_VAR(1) , BIRNET_SIG_ARG_TYPED_VAR(2) , BIRNET_SIG_ARG_TYPED_VAR(3) , BIRNET_SIG_ARG_TYPED_VAR(4) , BIRNET_SIG_ARG_TYPED_VAR(5) , BIRNET_SIG_ARG_TYPED_VAR(6)
#include <rapicorn/birnetsignaldefs.hh>
#undef BIRNET_SIG_c_TYPENAMES
#undef BIRNET_SIG_TYPENAMES
#undef BIRNET_SIG_c_TYPES
#undef BIRNET_SIG_TYPES
#undef BIRNET_SIG_c_VARS
#undef BIRNET_SIG_VARS
#undef BIRNET_SIG_c_TYPED_VARS
#undef BIRNET_SIG_TYPED_VARS
#endif // 6
#if   BIRNET_SIG_MATCH (7)
#undef BIRNET_SIG_NAME
#define BIRNET_SIG_NAME(x) x##7
#define BIRNET_SIG_c_TYPENAMES  BIRNET_SIG_ARG_c_TYPENAME(1)  BIRNET_SIG_ARG_c_TYPENAME(2)  BIRNET_SIG_ARG_c_TYPENAME(3)  BIRNET_SIG_ARG_c_TYPENAME(4)  BIRNET_SIG_ARG_c_TYPENAME(5)  BIRNET_SIG_ARG_c_TYPENAME(6)  BIRNET_SIG_ARG_c_TYPENAME(7)
#define BIRNET_SIG_TYPENAMES  BIRNET_SIG_ARG_TYPENAME(1) , BIRNET_SIG_ARG_TYPENAME(2) , BIRNET_SIG_ARG_TYPENAME(3) , BIRNET_SIG_ARG_TYPENAME(4) , BIRNET_SIG_ARG_TYPENAME(5) , BIRNET_SIG_ARG_TYPENAME(6) , BIRNET_SIG_ARG_TYPENAME(7)
#define BIRNET_SIG_c_TYPES  BIRNET_SIG_ARG_c_TYPE(1)  BIRNET_SIG_ARG_c_TYPE(2)  BIRNET_SIG_ARG_c_TYPE(3)  BIRNET_SIG_ARG_c_TYPE(4)  BIRNET_SIG_ARG_c_TYPE(5)  BIRNET_SIG_ARG_c_TYPE(6)  BIRNET_SIG_ARG_c_TYPE(7)
#define BIRNET_SIG_TYPES  BIRNET_SIG_ARG_TYPE(1) , BIRNET_SIG_ARG_TYPE(2) , BIRNET_SIG_ARG_TYPE(3) , BIRNET_SIG_ARG_TYPE(4) , BIRNET_SIG_ARG_TYPE(5) , BIRNET_SIG_ARG_TYPE(6) , BIRNET_SIG_ARG_TYPE(7)
#define BIRNET_SIG_c_VARS  BIRNET_SIG_ARG_c_VAR(1)  BIRNET_SIG_ARG_c_VAR(2)  BIRNET_SIG_ARG_c_VAR(3)  BIRNET_SIG_ARG_c_VAR(4)  BIRNET_SIG_ARG_c_VAR(5)  BIRNET_SIG_ARG_c_VAR(6)  BIRNET_SIG_ARG_c_VAR(7)
#define BIRNET_SIG_VARS  BIRNET_SIG_ARG_VAR(1) , BIRNET_SIG_ARG_VAR(2) , BIRNET_SIG_ARG_VAR(3) , BIRNET_SIG_ARG_VAR(4) , BIRNET_SIG_ARG_VAR(5) , BIRNET_SIG_ARG_VAR(6) , BIRNET_SIG_ARG_VAR(7)
#define BIRNET_SIG_c_TYPED_VARS  BIRNET_SIG_ARG_c_TYPED_VAR(1)  BIRNET_SIG_ARG_c_TYPED_VAR(2)  BIRNET_SIG_ARG_c_TYPED_VAR(3)  BIRNET_SIG_ARG_c_TYPED_VAR(4)  BIRNET_SIG_ARG_c_TYPED_VAR(5)  BIRNET_SIG_ARG_c_TYPED_VAR(6)  BIRNET_SIG_ARG_c_TYPED_VAR(7)
#define BIRNET_SIG_TYPED_VARS  BIRNET_SIG_ARG_TYPED_VAR(1) , BIRNET_SIG_ARG_TYPED_VAR(2) , BIRNET_SIG_ARG_TYPED_VAR(3) , BIRNET_SIG_ARG_TYPED_VAR(4) , BIRNET_SIG_ARG_TYPED_VAR(5) , BIRNET_SIG_ARG_TYPED_VAR(6) , BIRNET_SIG_ARG_TYPED_VAR(7)
#include <rapicorn/birnetsignaldefs.hh>
#undef BIRNET_SIG_c_TYPENAMES
#undef BIRNET_SIG_TYPENAMES
#undef BIRNET_SIG_c_TYPES
#undef BIRNET_SIG_TYPES
#undef BIRNET_SIG_c_VARS
#undef BIRNET_SIG_VARS
#undef BIRNET_SIG_c_TYPED_VARS
#undef BIRNET_SIG_TYPED_VARS
#endif // 7
#if   BIRNET_SIG_MATCH (8)
#undef BIRNET_SIG_NAME
#define BIRNET_SIG_NAME(x) x##8
#define BIRNET_SIG_c_TYPENAMES  BIRNET_SIG_ARG_c_TYPENAME(1)  BIRNET_SIG_ARG_c_TYPENAME(2)  BIRNET_SIG_ARG_c_TYPENAME(3)  BIRNET_SIG_ARG_c_TYPENAME(4)  BIRNET_SIG_ARG_c_TYPENAME(5)  BIRNET_SIG_ARG_c_TYPENAME(6)  BIRNET_SIG_ARG_c_TYPENAME(7)  BIRNET_SIG_ARG_c_TYPENAME(8)
#define BIRNET_SIG_TYPENAMES  BIRNET_SIG_ARG_TYPENAME(1) , BIRNET_SIG_ARG_TYPENAME(2) , BIRNET_SIG_ARG_TYPENAME(3) , BIRNET_SIG_ARG_TYPENAME(4) , BIRNET_SIG_ARG_TYPENAME(5) , BIRNET_SIG_ARG_TYPENAME(6) , BIRNET_SIG_ARG_TYPENAME(7) , BIRNET_SIG_ARG_TYPENAME(8)
#define BIRNET_SIG_c_TYPES  BIRNET_SIG_ARG_c_TYPE(1)  BIRNET_SIG_ARG_c_TYPE(2)  BIRNET_SIG_ARG_c_TYPE(3)  BIRNET_SIG_ARG_c_TYPE(4)  BIRNET_SIG_ARG_c_TYPE(5)  BIRNET_SIG_ARG_c_TYPE(6)  BIRNET_SIG_ARG_c_TYPE(7)  BIRNET_SIG_ARG_c_TYPE(8)
#define BIRNET_SIG_TYPES  BIRNET_SIG_ARG_TYPE(1) , BIRNET_SIG_ARG_TYPE(2) , BIRNET_SIG_ARG_TYPE(3) , BIRNET_SIG_ARG_TYPE(4) , BIRNET_SIG_ARG_TYPE(5) , BIRNET_SIG_ARG_TYPE(6) , BIRNET_SIG_ARG_TYPE(7) , BIRNET_SIG_ARG_TYPE(8)
#define BIRNET_SIG_c_VARS  BIRNET_SIG_ARG_c_VAR(1)  BIRNET_SIG_ARG_c_VAR(2)  BIRNET_SIG_ARG_c_VAR(3)  BIRNET_SIG_ARG_c_VAR(4)  BIRNET_SIG_ARG_c_VAR(5)  BIRNET_SIG_ARG_c_VAR(6)  BIRNET_SIG_ARG_c_VAR(7)  BIRNET_SIG_ARG_c_VAR(8)
#define BIRNET_SIG_VARS  BIRNET_SIG_ARG_VAR(1) , BIRNET_SIG_ARG_VAR(2) , BIRNET_SIG_ARG_VAR(3) , BIRNET_SIG_ARG_VAR(4) , BIRNET_SIG_ARG_VAR(5) , BIRNET_SIG_ARG_VAR(6) , BIRNET_SIG_ARG_VAR(7) , BIRNET_SIG_ARG_VAR(8)
#define BIRNET_SIG_c_TYPED_VARS  BIRNET_SIG_ARG_c_TYPED_VAR(1)  BIRNET_SIG_ARG_c_TYPED_VAR(2)  BIRNET_SIG_ARG_c_TYPED_VAR(3)  BIRNET_SIG_ARG_c_TYPED_VAR(4)  BIRNET_SIG_ARG_c_TYPED_VAR(5)  BIRNET_SIG_ARG_c_TYPED_VAR(6)  BIRNET_SIG_ARG_c_TYPED_VAR(7)  BIRNET_SIG_ARG_c_TYPED_VAR(8)
#define BIRNET_SIG_TYPED_VARS  BIRNET_SIG_ARG_TYPED_VAR(1) , BIRNET_SIG_ARG_TYPED_VAR(2) , BIRNET_SIG_ARG_TYPED_VAR(3) , BIRNET_SIG_ARG_TYPED_VAR(4) , BIRNET_SIG_ARG_TYPED_VAR(5) , BIRNET_SIG_ARG_TYPED_VAR(6) , BIRNET_SIG_ARG_TYPED_VAR(7) , BIRNET_SIG_ARG_TYPED_VAR(8)
#include <rapicorn/birnetsignaldefs.hh>
#undef BIRNET_SIG_c_TYPENAMES
#undef BIRNET_SIG_TYPENAMES
#undef BIRNET_SIG_c_TYPES
#undef BIRNET_SIG_TYPES
#undef BIRNET_SIG_c_VARS
#undef BIRNET_SIG_VARS
#undef BIRNET_SIG_c_TYPED_VARS
#undef BIRNET_SIG_TYPED_VARS
#endif // 8
#if   BIRNET_SIG_MATCH (9)
#undef BIRNET_SIG_NAME
#define BIRNET_SIG_NAME(x) x##9
#define BIRNET_SIG_c_TYPENAMES  BIRNET_SIG_ARG_c_TYPENAME(1)  BIRNET_SIG_ARG_c_TYPENAME(2)  BIRNET_SIG_ARG_c_TYPENAME(3)  BIRNET_SIG_ARG_c_TYPENAME(4)  BIRNET_SIG_ARG_c_TYPENAME(5)  BIRNET_SIG_ARG_c_TYPENAME(6)  BIRNET_SIG_ARG_c_TYPENAME(7)  BIRNET_SIG_ARG_c_TYPENAME(8)  BIRNET_SIG_ARG_c_TYPENAME(9)
#define BIRNET_SIG_TYPENAMES  BIRNET_SIG_ARG_TYPENAME(1) , BIRNET_SIG_ARG_TYPENAME(2) , BIRNET_SIG_ARG_TYPENAME(3) , BIRNET_SIG_ARG_TYPENAME(4) , BIRNET_SIG_ARG_TYPENAME(5) , BIRNET_SIG_ARG_TYPENAME(6) , BIRNET_SIG_ARG_TYPENAME(7) , BIRNET_SIG_ARG_TYPENAME(8) , BIRNET_SIG_ARG_TYPENAME(9)
#define BIRNET_SIG_c_TYPES  BIRNET_SIG_ARG_c_TYPE(1)  BIRNET_SIG_ARG_c_TYPE(2)  BIRNET_SIG_ARG_c_TYPE(3)  BIRNET_SIG_ARG_c_TYPE(4)  BIRNET_SIG_ARG_c_TYPE(5)  BIRNET_SIG_ARG_c_TYPE(6)  BIRNET_SIG_ARG_c_TYPE(7)  BIRNET_SIG_ARG_c_TYPE(8)  BIRNET_SIG_ARG_c_TYPE(9)
#define BIRNET_SIG_TYPES  BIRNET_SIG_ARG_TYPE(1) , BIRNET_SIG_ARG_TYPE(2) , BIRNET_SIG_ARG_TYPE(3) , BIRNET_SIG_ARG_TYPE(4) , BIRNET_SIG_ARG_TYPE(5) , BIRNET_SIG_ARG_TYPE(6) , BIRNET_SIG_ARG_TYPE(7) , BIRNET_SIG_ARG_TYPE(8) , BIRNET_SIG_ARG_TYPE(9)
#define BIRNET_SIG_c_VARS  BIRNET_SIG_ARG_c_VAR(1)  BIRNET_SIG_ARG_c_VAR(2)  BIRNET_SIG_ARG_c_VAR(3)  BIRNET_SIG_ARG_c_VAR(4)  BIRNET_SIG_ARG_c_VAR(5)  BIRNET_SIG_ARG_c_VAR(6)  BIRNET_SIG_ARG_c_VAR(7)  BIRNET_SIG_ARG_c_VAR(8)  BIRNET_SIG_ARG_c_VAR(9)
#define BIRNET_SIG_VARS  BIRNET_SIG_ARG_VAR(1) , BIRNET_SIG_ARG_VAR(2) , BIRNET_SIG_ARG_VAR(3) , BIRNET_SIG_ARG_VAR(4) , BIRNET_SIG_ARG_VAR(5) , BIRNET_SIG_ARG_VAR(6) , BIRNET_SIG_ARG_VAR(7) , BIRNET_SIG_ARG_VAR(8) , BIRNET_SIG_ARG_VAR(9)
#define BIRNET_SIG_c_TYPED_VARS  BIRNET_SIG_ARG_c_TYPED_VAR(1)  BIRNET_SIG_ARG_c_TYPED_VAR(2)  BIRNET_SIG_ARG_c_TYPED_VAR(3)  BIRNET_SIG_ARG_c_TYPED_VAR(4)  BIRNET_SIG_ARG_c_TYPED_VAR(5)  BIRNET_SIG_ARG_c_TYPED_VAR(6)  BIRNET_SIG_ARG_c_TYPED_VAR(7)  BIRNET_SIG_ARG_c_TYPED_VAR(8)  BIRNET_SIG_ARG_c_TYPED_VAR(9)
#define BIRNET_SIG_TYPED_VARS  BIRNET_SIG_ARG_TYPED_VAR(1) , BIRNET_SIG_ARG_TYPED_VAR(2) , BIRNET_SIG_ARG_TYPED_VAR(3) , BIRNET_SIG_ARG_TYPED_VAR(4) , BIRNET_SIG_ARG_TYPED_VAR(5) , BIRNET_SIG_ARG_TYPED_VAR(6) , BIRNET_SIG_ARG_TYPED_VAR(7) , BIRNET_SIG_ARG_TYPED_VAR(8) , BIRNET_SIG_ARG_TYPED_VAR(9)
#include <rapicorn/birnetsignaldefs.hh>
#undef BIRNET_SIG_c_TYPENAMES
#undef BIRNET_SIG_TYPENAMES
#undef BIRNET_SIG_c_TYPES
#undef BIRNET_SIG_TYPES
#undef BIRNET_SIG_c_VARS
#undef BIRNET_SIG_VARS
#undef BIRNET_SIG_c_TYPED_VARS
#undef BIRNET_SIG_TYPED_VARS
#endif // 9
#if   BIRNET_SIG_MATCH (10)
#undef BIRNET_SIG_NAME
#define BIRNET_SIG_NAME(x) x##10
#define BIRNET_SIG_c_TYPENAMES  BIRNET_SIG_ARG_c_TYPENAME(1)  BIRNET_SIG_ARG_c_TYPENAME(2)  BIRNET_SIG_ARG_c_TYPENAME(3)  BIRNET_SIG_ARG_c_TYPENAME(4)  BIRNET_SIG_ARG_c_TYPENAME(5)  BIRNET_SIG_ARG_c_TYPENAME(6)  BIRNET_SIG_ARG_c_TYPENAME(7)  BIRNET_SIG_ARG_c_TYPENAME(8)  BIRNET_SIG_ARG_c_TYPENAME(9)  BIRNET_SIG_ARG_c_TYPENAME(10)
#define BIRNET_SIG_TYPENAMES  BIRNET_SIG_ARG_TYPENAME(1) , BIRNET_SIG_ARG_TYPENAME(2) , BIRNET_SIG_ARG_TYPENAME(3) , BIRNET_SIG_ARG_TYPENAME(4) , BIRNET_SIG_ARG_TYPENAME(5) , BIRNET_SIG_ARG_TYPENAME(6) , BIRNET_SIG_ARG_TYPENAME(7) , BIRNET_SIG_ARG_TYPENAME(8) , BIRNET_SIG_ARG_TYPENAME(9) , BIRNET_SIG_ARG_TYPENAME(10)
#define BIRNET_SIG_c_TYPES  BIRNET_SIG_ARG_c_TYPE(1)  BIRNET_SIG_ARG_c_TYPE(2)  BIRNET_SIG_ARG_c_TYPE(3)  BIRNET_SIG_ARG_c_TYPE(4)  BIRNET_SIG_ARG_c_TYPE(5)  BIRNET_SIG_ARG_c_TYPE(6)  BIRNET_SIG_ARG_c_TYPE(7)  BIRNET_SIG_ARG_c_TYPE(8)  BIRNET_SIG_ARG_c_TYPE(9)  BIRNET_SIG_ARG_c_TYPE(10)
#define BIRNET_SIG_TYPES  BIRNET_SIG_ARG_TYPE(1) , BIRNET_SIG_ARG_TYPE(2) , BIRNET_SIG_ARG_TYPE(3) , BIRNET_SIG_ARG_TYPE(4) , BIRNET_SIG_ARG_TYPE(5) , BIRNET_SIG_ARG_TYPE(6) , BIRNET_SIG_ARG_TYPE(7) , BIRNET_SIG_ARG_TYPE(8) , BIRNET_SIG_ARG_TYPE(9) , BIRNET_SIG_ARG_TYPE(10)
#define BIRNET_SIG_c_VARS  BIRNET_SIG_ARG_c_VAR(1)  BIRNET_SIG_ARG_c_VAR(2)  BIRNET_SIG_ARG_c_VAR(3)  BIRNET_SIG_ARG_c_VAR(4)  BIRNET_SIG_ARG_c_VAR(5)  BIRNET_SIG_ARG_c_VAR(6)  BIRNET_SIG_ARG_c_VAR(7)  BIRNET_SIG_ARG_c_VAR(8)  BIRNET_SIG_ARG_c_VAR(9)  BIRNET_SIG_ARG_c_VAR(10)
#define BIRNET_SIG_VARS  BIRNET_SIG_ARG_VAR(1) , BIRNET_SIG_ARG_VAR(2) , BIRNET_SIG_ARG_VAR(3) , BIRNET_SIG_ARG_VAR(4) , BIRNET_SIG_ARG_VAR(5) , BIRNET_SIG_ARG_VAR(6) , BIRNET_SIG_ARG_VAR(7) , BIRNET_SIG_ARG_VAR(8) , BIRNET_SIG_ARG_VAR(9) , BIRNET_SIG_ARG_VAR(10)
#define BIRNET_SIG_c_TYPED_VARS  BIRNET_SIG_ARG_c_TYPED_VAR(1)  BIRNET_SIG_ARG_c_TYPED_VAR(2)  BIRNET_SIG_ARG_c_TYPED_VAR(3)  BIRNET_SIG_ARG_c_TYPED_VAR(4)  BIRNET_SIG_ARG_c_TYPED_VAR(5)  BIRNET_SIG_ARG_c_TYPED_VAR(6)  BIRNET_SIG_ARG_c_TYPED_VAR(7)  BIRNET_SIG_ARG_c_TYPED_VAR(8)  BIRNET_SIG_ARG_c_TYPED_VAR(9)  BIRNET_SIG_ARG_c_TYPED_VAR(10)
#define BIRNET_SIG_TYPED_VARS  BIRNET_SIG_ARG_TYPED_VAR(1) , BIRNET_SIG_ARG_TYPED_VAR(2) , BIRNET_SIG_ARG_TYPED_VAR(3) , BIRNET_SIG_ARG_TYPED_VAR(4) , BIRNET_SIG_ARG_TYPED_VAR(5) , BIRNET_SIG_ARG_TYPED_VAR(6) , BIRNET_SIG_ARG_TYPED_VAR(7) , BIRNET_SIG_ARG_TYPED_VAR(8) , BIRNET_SIG_ARG_TYPED_VAR(9) , BIRNET_SIG_ARG_TYPED_VAR(10)
#include <rapicorn/birnetsignaldefs.hh>
#undef BIRNET_SIG_c_TYPENAMES
#undef BIRNET_SIG_TYPENAMES
#undef BIRNET_SIG_c_TYPES
#undef BIRNET_SIG_TYPES
#undef BIRNET_SIG_c_VARS
#undef BIRNET_SIG_VARS
#undef BIRNET_SIG_c_TYPED_VARS
#undef BIRNET_SIG_TYPED_VARS
#endif // 10
#if   BIRNET_SIG_MATCH (11)
#undef BIRNET_SIG_NAME
#define BIRNET_SIG_NAME(x) x##11
#define BIRNET_SIG_c_TYPENAMES  BIRNET_SIG_ARG_c_TYPENAME(1)  BIRNET_SIG_ARG_c_TYPENAME(2)  BIRNET_SIG_ARG_c_TYPENAME(3)  BIRNET_SIG_ARG_c_TYPENAME(4)  BIRNET_SIG_ARG_c_TYPENAME(5)  BIRNET_SIG_ARG_c_TYPENAME(6)  BIRNET_SIG_ARG_c_TYPENAME(7)  BIRNET_SIG_ARG_c_TYPENAME(8)  BIRNET_SIG_ARG_c_TYPENAME(9)  BIRNET_SIG_ARG_c_TYPENAME(10)  BIRNET_SIG_ARG_c_TYPENAME(11)
#define BIRNET_SIG_TYPENAMES  BIRNET_SIG_ARG_TYPENAME(1) , BIRNET_SIG_ARG_TYPENAME(2) , BIRNET_SIG_ARG_TYPENAME(3) , BIRNET_SIG_ARG_TYPENAME(4) , BIRNET_SIG_ARG_TYPENAME(5) , BIRNET_SIG_ARG_TYPENAME(6) , BIRNET_SIG_ARG_TYPENAME(7) , BIRNET_SIG_ARG_TYPENAME(8) , BIRNET_SIG_ARG_TYPENAME(9) , BIRNET_SIG_ARG_TYPENAME(10) , BIRNET_SIG_ARG_TYPENAME(11)
#define BIRNET_SIG_c_TYPES  BIRNET_SIG_ARG_c_TYPE(1)  BIRNET_SIG_ARG_c_TYPE(2)  BIRNET_SIG_ARG_c_TYPE(3)  BIRNET_SIG_ARG_c_TYPE(4)  BIRNET_SIG_ARG_c_TYPE(5)  BIRNET_SIG_ARG_c_TYPE(6)  BIRNET_SIG_ARG_c_TYPE(7)  BIRNET_SIG_ARG_c_TYPE(8)  BIRNET_SIG_ARG_c_TYPE(9)  BIRNET_SIG_ARG_c_TYPE(10)  BIRNET_SIG_ARG_c_TYPE(11)
#define BIRNET_SIG_TYPES  BIRNET_SIG_ARG_TYPE(1) , BIRNET_SIG_ARG_TYPE(2) , BIRNET_SIG_ARG_TYPE(3) , BIRNET_SIG_ARG_TYPE(4) , BIRNET_SIG_ARG_TYPE(5) , BIRNET_SIG_ARG_TYPE(6) , BIRNET_SIG_ARG_TYPE(7) , BIRNET_SIG_ARG_TYPE(8) , BIRNET_SIG_ARG_TYPE(9) , BIRNET_SIG_ARG_TYPE(10) , BIRNET_SIG_ARG_TYPE(11)
#define BIRNET_SIG_c_VARS  BIRNET_SIG_ARG_c_VAR(1)  BIRNET_SIG_ARG_c_VAR(2)  BIRNET_SIG_ARG_c_VAR(3)  BIRNET_SIG_ARG_c_VAR(4)  BIRNET_SIG_ARG_c_VAR(5)  BIRNET_SIG_ARG_c_VAR(6)  BIRNET_SIG_ARG_c_VAR(7)  BIRNET_SIG_ARG_c_VAR(8)  BIRNET_SIG_ARG_c_VAR(9)  BIRNET_SIG_ARG_c_VAR(10)  BIRNET_SIG_ARG_c_VAR(11)
#define BIRNET_SIG_VARS  BIRNET_SIG_ARG_VAR(1) , BIRNET_SIG_ARG_VAR(2) , BIRNET_SIG_ARG_VAR(3) , BIRNET_SIG_ARG_VAR(4) , BIRNET_SIG_ARG_VAR(5) , BIRNET_SIG_ARG_VAR(6) , BIRNET_SIG_ARG_VAR(7) , BIRNET_SIG_ARG_VAR(8) , BIRNET_SIG_ARG_VAR(9) , BIRNET_SIG_ARG_VAR(10) , BIRNET_SIG_ARG_VAR(11)
#define BIRNET_SIG_c_TYPED_VARS  BIRNET_SIG_ARG_c_TYPED_VAR(1)  BIRNET_SIG_ARG_c_TYPED_VAR(2)  BIRNET_SIG_ARG_c_TYPED_VAR(3)  BIRNET_SIG_ARG_c_TYPED_VAR(4)  BIRNET_SIG_ARG_c_TYPED_VAR(5)  BIRNET_SIG_ARG_c_TYPED_VAR(6)  BIRNET_SIG_ARG_c_TYPED_VAR(7)  BIRNET_SIG_ARG_c_TYPED_VAR(8)  BIRNET_SIG_ARG_c_TYPED_VAR(9)  BIRNET_SIG_ARG_c_TYPED_VAR(10)  BIRNET_SIG_ARG_c_TYPED_VAR(11)
#define BIRNET_SIG_TYPED_VARS  BIRNET_SIG_ARG_TYPED_VAR(1) , BIRNET_SIG_ARG_TYPED_VAR(2) , BIRNET_SIG_ARG_TYPED_VAR(3) , BIRNET_SIG_ARG_TYPED_VAR(4) , BIRNET_SIG_ARG_TYPED_VAR(5) , BIRNET_SIG_ARG_TYPED_VAR(6) , BIRNET_SIG_ARG_TYPED_VAR(7) , BIRNET_SIG_ARG_TYPED_VAR(8) , BIRNET_SIG_ARG_TYPED_VAR(9) , BIRNET_SIG_ARG_TYPED_VAR(10) , BIRNET_SIG_ARG_TYPED_VAR(11)
#include <rapicorn/birnetsignaldefs.hh>
#undef BIRNET_SIG_c_TYPENAMES
#undef BIRNET_SIG_TYPENAMES
#undef BIRNET_SIG_c_TYPES
#undef BIRNET_SIG_TYPES
#undef BIRNET_SIG_c_VARS
#undef BIRNET_SIG_VARS
#undef BIRNET_SIG_c_TYPED_VARS
#undef BIRNET_SIG_TYPED_VARS
#endif // 11
#if   BIRNET_SIG_MATCH (12)
#undef BIRNET_SIG_NAME
#define BIRNET_SIG_NAME(x) x##12
#define BIRNET_SIG_c_TYPENAMES  BIRNET_SIG_ARG_c_TYPENAME(1)  BIRNET_SIG_ARG_c_TYPENAME(2)  BIRNET_SIG_ARG_c_TYPENAME(3)  BIRNET_SIG_ARG_c_TYPENAME(4)  BIRNET_SIG_ARG_c_TYPENAME(5)  BIRNET_SIG_ARG_c_TYPENAME(6)  BIRNET_SIG_ARG_c_TYPENAME(7)  BIRNET_SIG_ARG_c_TYPENAME(8)  BIRNET_SIG_ARG_c_TYPENAME(9)  BIRNET_SIG_ARG_c_TYPENAME(10)  BIRNET_SIG_ARG_c_TYPENAME(11)  BIRNET_SIG_ARG_c_TYPENAME(12)
#define BIRNET_SIG_TYPENAMES  BIRNET_SIG_ARG_TYPENAME(1) , BIRNET_SIG_ARG_TYPENAME(2) , BIRNET_SIG_ARG_TYPENAME(3) , BIRNET_SIG_ARG_TYPENAME(4) , BIRNET_SIG_ARG_TYPENAME(5) , BIRNET_SIG_ARG_TYPENAME(6) , BIRNET_SIG_ARG_TYPENAME(7) , BIRNET_SIG_ARG_TYPENAME(8) , BIRNET_SIG_ARG_TYPENAME(9) , BIRNET_SIG_ARG_TYPENAME(10) , BIRNET_SIG_ARG_TYPENAME(11) , BIRNET_SIG_ARG_TYPENAME(12)
#define BIRNET_SIG_c_TYPES  BIRNET_SIG_ARG_c_TYPE(1)  BIRNET_SIG_ARG_c_TYPE(2)  BIRNET_SIG_ARG_c_TYPE(3)  BIRNET_SIG_ARG_c_TYPE(4)  BIRNET_SIG_ARG_c_TYPE(5)  BIRNET_SIG_ARG_c_TYPE(6)  BIRNET_SIG_ARG_c_TYPE(7)  BIRNET_SIG_ARG_c_TYPE(8)  BIRNET_SIG_ARG_c_TYPE(9)  BIRNET_SIG_ARG_c_TYPE(10)  BIRNET_SIG_ARG_c_TYPE(11)  BIRNET_SIG_ARG_c_TYPE(12)
#define BIRNET_SIG_TYPES  BIRNET_SIG_ARG_TYPE(1) , BIRNET_SIG_ARG_TYPE(2) , BIRNET_SIG_ARG_TYPE(3) , BIRNET_SIG_ARG_TYPE(4) , BIRNET_SIG_ARG_TYPE(5) , BIRNET_SIG_ARG_TYPE(6) , BIRNET_SIG_ARG_TYPE(7) , BIRNET_SIG_ARG_TYPE(8) , BIRNET_SIG_ARG_TYPE(9) , BIRNET_SIG_ARG_TYPE(10) , BIRNET_SIG_ARG_TYPE(11) , BIRNET_SIG_ARG_TYPE(12)
#define BIRNET_SIG_c_VARS  BIRNET_SIG_ARG_c_VAR(1)  BIRNET_SIG_ARG_c_VAR(2)  BIRNET_SIG_ARG_c_VAR(3)  BIRNET_SIG_ARG_c_VAR(4)  BIRNET_SIG_ARG_c_VAR(5)  BIRNET_SIG_ARG_c_VAR(6)  BIRNET_SIG_ARG_c_VAR(7)  BIRNET_SIG_ARG_c_VAR(8)  BIRNET_SIG_ARG_c_VAR(9)  BIRNET_SIG_ARG_c_VAR(10)  BIRNET_SIG_ARG_c_VAR(11)  BIRNET_SIG_ARG_c_VAR(12)
#define BIRNET_SIG_VARS  BIRNET_SIG_ARG_VAR(1) , BIRNET_SIG_ARG_VAR(2) , BIRNET_SIG_ARG_VAR(3) , BIRNET_SIG_ARG_VAR(4) , BIRNET_SIG_ARG_VAR(5) , BIRNET_SIG_ARG_VAR(6) , BIRNET_SIG_ARG_VAR(7) , BIRNET_SIG_ARG_VAR(8) , BIRNET_SIG_ARG_VAR(9) , BIRNET_SIG_ARG_VAR(10) , BIRNET_SIG_ARG_VAR(11) , BIRNET_SIG_ARG_VAR(12)
#define BIRNET_SIG_c_TYPED_VARS  BIRNET_SIG_ARG_c_TYPED_VAR(1)  BIRNET_SIG_ARG_c_TYPED_VAR(2)  BIRNET_SIG_ARG_c_TYPED_VAR(3)  BIRNET_SIG_ARG_c_TYPED_VAR(4)  BIRNET_SIG_ARG_c_TYPED_VAR(5)  BIRNET_SIG_ARG_c_TYPED_VAR(6)  BIRNET_SIG_ARG_c_TYPED_VAR(7)  BIRNET_SIG_ARG_c_TYPED_VAR(8)  BIRNET_SIG_ARG_c_TYPED_VAR(9)  BIRNET_SIG_ARG_c_TYPED_VAR(10)  BIRNET_SIG_ARG_c_TYPED_VAR(11)  BIRNET_SIG_ARG_c_TYPED_VAR(12)
#define BIRNET_SIG_TYPED_VARS  BIRNET_SIG_ARG_TYPED_VAR(1) , BIRNET_SIG_ARG_TYPED_VAR(2) , BIRNET_SIG_ARG_TYPED_VAR(3) , BIRNET_SIG_ARG_TYPED_VAR(4) , BIRNET_SIG_ARG_TYPED_VAR(5) , BIRNET_SIG_ARG_TYPED_VAR(6) , BIRNET_SIG_ARG_TYPED_VAR(7) , BIRNET_SIG_ARG_TYPED_VAR(8) , BIRNET_SIG_ARG_TYPED_VAR(9) , BIRNET_SIG_ARG_TYPED_VAR(10) , BIRNET_SIG_ARG_TYPED_VAR(11) , BIRNET_SIG_ARG_TYPED_VAR(12)
#include <rapicorn/birnetsignaldefs.hh>
#undef BIRNET_SIG_c_TYPENAMES
#undef BIRNET_SIG_TYPENAMES
#undef BIRNET_SIG_c_TYPES
#undef BIRNET_SIG_TYPES
#undef BIRNET_SIG_c_VARS
#undef BIRNET_SIG_VARS
#undef BIRNET_SIG_c_TYPED_VARS
#undef BIRNET_SIG_TYPED_VARS
#endif // 12
#if   BIRNET_SIG_MATCH (13)
#undef BIRNET_SIG_NAME
#define BIRNET_SIG_NAME(x) x##13
#define BIRNET_SIG_c_TYPENAMES  BIRNET_SIG_ARG_c_TYPENAME(1)  BIRNET_SIG_ARG_c_TYPENAME(2)  BIRNET_SIG_ARG_c_TYPENAME(3)  BIRNET_SIG_ARG_c_TYPENAME(4)  BIRNET_SIG_ARG_c_TYPENAME(5)  BIRNET_SIG_ARG_c_TYPENAME(6)  BIRNET_SIG_ARG_c_TYPENAME(7)  BIRNET_SIG_ARG_c_TYPENAME(8)  BIRNET_SIG_ARG_c_TYPENAME(9)  BIRNET_SIG_ARG_c_TYPENAME(10)  BIRNET_SIG_ARG_c_TYPENAME(11)  BIRNET_SIG_ARG_c_TYPENAME(12)  BIRNET_SIG_ARG_c_TYPENAME(13)
#define BIRNET_SIG_TYPENAMES  BIRNET_SIG_ARG_TYPENAME(1) , BIRNET_SIG_ARG_TYPENAME(2) , BIRNET_SIG_ARG_TYPENAME(3) , BIRNET_SIG_ARG_TYPENAME(4) , BIRNET_SIG_ARG_TYPENAME(5) , BIRNET_SIG_ARG_TYPENAME(6) , BIRNET_SIG_ARG_TYPENAME(7) , BIRNET_SIG_ARG_TYPENAME(8) , BIRNET_SIG_ARG_TYPENAME(9) , BIRNET_SIG_ARG_TYPENAME(10) , BIRNET_SIG_ARG_TYPENAME(11) , BIRNET_SIG_ARG_TYPENAME(12) , BIRNET_SIG_ARG_TYPENAME(13)
#define BIRNET_SIG_c_TYPES  BIRNET_SIG_ARG_c_TYPE(1)  BIRNET_SIG_ARG_c_TYPE(2)  BIRNET_SIG_ARG_c_TYPE(3)  BIRNET_SIG_ARG_c_TYPE(4)  BIRNET_SIG_ARG_c_TYPE(5)  BIRNET_SIG_ARG_c_TYPE(6)  BIRNET_SIG_ARG_c_TYPE(7)  BIRNET_SIG_ARG_c_TYPE(8)  BIRNET_SIG_ARG_c_TYPE(9)  BIRNET_SIG_ARG_c_TYPE(10)  BIRNET_SIG_ARG_c_TYPE(11)  BIRNET_SIG_ARG_c_TYPE(12)  BIRNET_SIG_ARG_c_TYPE(13)
#define BIRNET_SIG_TYPES  BIRNET_SIG_ARG_TYPE(1) , BIRNET_SIG_ARG_TYPE(2) , BIRNET_SIG_ARG_TYPE(3) , BIRNET_SIG_ARG_TYPE(4) , BIRNET_SIG_ARG_TYPE(5) , BIRNET_SIG_ARG_TYPE(6) , BIRNET_SIG_ARG_TYPE(7) , BIRNET_SIG_ARG_TYPE(8) , BIRNET_SIG_ARG_TYPE(9) , BIRNET_SIG_ARG_TYPE(10) , BIRNET_SIG_ARG_TYPE(11) , BIRNET_SIG_ARG_TYPE(12) , BIRNET_SIG_ARG_TYPE(13)
#define BIRNET_SIG_c_VARS  BIRNET_SIG_ARG_c_VAR(1)  BIRNET_SIG_ARG_c_VAR(2)  BIRNET_SIG_ARG_c_VAR(3)  BIRNET_SIG_ARG_c_VAR(4)  BIRNET_SIG_ARG_c_VAR(5)  BIRNET_SIG_ARG_c_VAR(6)  BIRNET_SIG_ARG_c_VAR(7)  BIRNET_SIG_ARG_c_VAR(8)  BIRNET_SIG_ARG_c_VAR(9)  BIRNET_SIG_ARG_c_VAR(10)  BIRNET_SIG_ARG_c_VAR(11)  BIRNET_SIG_ARG_c_VAR(12)  BIRNET_SIG_ARG_c_VAR(13)
#define BIRNET_SIG_VARS  BIRNET_SIG_ARG_VAR(1) , BIRNET_SIG_ARG_VAR(2) , BIRNET_SIG_ARG_VAR(3) , BIRNET_SIG_ARG_VAR(4) , BIRNET_SIG_ARG_VAR(5) , BIRNET_SIG_ARG_VAR(6) , BIRNET_SIG_ARG_VAR(7) , BIRNET_SIG_ARG_VAR(8) , BIRNET_SIG_ARG_VAR(9) , BIRNET_SIG_ARG_VAR(10) , BIRNET_SIG_ARG_VAR(11) , BIRNET_SIG_ARG_VAR(12) , BIRNET_SIG_ARG_VAR(13)
#define BIRNET_SIG_c_TYPED_VARS  BIRNET_SIG_ARG_c_TYPED_VAR(1)  BIRNET_SIG_ARG_c_TYPED_VAR(2)  BIRNET_SIG_ARG_c_TYPED_VAR(3)  BIRNET_SIG_ARG_c_TYPED_VAR(4)  BIRNET_SIG_ARG_c_TYPED_VAR(5)  BIRNET_SIG_ARG_c_TYPED_VAR(6)  BIRNET_SIG_ARG_c_TYPED_VAR(7)  BIRNET_SIG_ARG_c_TYPED_VAR(8)  BIRNET_SIG_ARG_c_TYPED_VAR(9)  BIRNET_SIG_ARG_c_TYPED_VAR(10)  BIRNET_SIG_ARG_c_TYPED_VAR(11)  BIRNET_SIG_ARG_c_TYPED_VAR(12)  BIRNET_SIG_ARG_c_TYPED_VAR(13)
#define BIRNET_SIG_TYPED_VARS  BIRNET_SIG_ARG_TYPED_VAR(1) , BIRNET_SIG_ARG_TYPED_VAR(2) , BIRNET_SIG_ARG_TYPED_VAR(3) , BIRNET_SIG_ARG_TYPED_VAR(4) , BIRNET_SIG_ARG_TYPED_VAR(5) , BIRNET_SIG_ARG_TYPED_VAR(6) , BIRNET_SIG_ARG_TYPED_VAR(7) , BIRNET_SIG_ARG_TYPED_VAR(8) , BIRNET_SIG_ARG_TYPED_VAR(9) , BIRNET_SIG_ARG_TYPED_VAR(10) , BIRNET_SIG_ARG_TYPED_VAR(11) , BIRNET_SIG_ARG_TYPED_VAR(12) , BIRNET_SIG_ARG_TYPED_VAR(13)
#include <rapicorn/birnetsignaldefs.hh>
#undef BIRNET_SIG_c_TYPENAMES
#undef BIRNET_SIG_TYPENAMES
#undef BIRNET_SIG_c_TYPES
#undef BIRNET_SIG_TYPES
#undef BIRNET_SIG_c_VARS
#undef BIRNET_SIG_VARS
#undef BIRNET_SIG_c_TYPED_VARS
#undef BIRNET_SIG_TYPED_VARS
#endif // 13
#if   BIRNET_SIG_MATCH (14)
#undef BIRNET_SIG_NAME
#define BIRNET_SIG_NAME(x) x##14
#define BIRNET_SIG_c_TYPENAMES  BIRNET_SIG_ARG_c_TYPENAME(1)  BIRNET_SIG_ARG_c_TYPENAME(2)  BIRNET_SIG_ARG_c_TYPENAME(3)  BIRNET_SIG_ARG_c_TYPENAME(4)  BIRNET_SIG_ARG_c_TYPENAME(5)  BIRNET_SIG_ARG_c_TYPENAME(6)  BIRNET_SIG_ARG_c_TYPENAME(7)  BIRNET_SIG_ARG_c_TYPENAME(8)  BIRNET_SIG_ARG_c_TYPENAME(9)  BIRNET_SIG_ARG_c_TYPENAME(10)  BIRNET_SIG_ARG_c_TYPENAME(11)  BIRNET_SIG_ARG_c_TYPENAME(12)  BIRNET_SIG_ARG_c_TYPENAME(13)  BIRNET_SIG_ARG_c_TYPENAME(14)
#define BIRNET_SIG_TYPENAMES  BIRNET_SIG_ARG_TYPENAME(1) , BIRNET_SIG_ARG_TYPENAME(2) , BIRNET_SIG_ARG_TYPENAME(3) , BIRNET_SIG_ARG_TYPENAME(4) , BIRNET_SIG_ARG_TYPENAME(5) , BIRNET_SIG_ARG_TYPENAME(6) , BIRNET_SIG_ARG_TYPENAME(7) , BIRNET_SIG_ARG_TYPENAME(8) , BIRNET_SIG_ARG_TYPENAME(9) , BIRNET_SIG_ARG_TYPENAME(10) , BIRNET_SIG_ARG_TYPENAME(11) , BIRNET_SIG_ARG_TYPENAME(12) , BIRNET_SIG_ARG_TYPENAME(13) , BIRNET_SIG_ARG_TYPENAME(14)
#define BIRNET_SIG_c_TYPES  BIRNET_SIG_ARG_c_TYPE(1)  BIRNET_SIG_ARG_c_TYPE(2)  BIRNET_SIG_ARG_c_TYPE(3)  BIRNET_SIG_ARG_c_TYPE(4)  BIRNET_SIG_ARG_c_TYPE(5)  BIRNET_SIG_ARG_c_TYPE(6)  BIRNET_SIG_ARG_c_TYPE(7)  BIRNET_SIG_ARG_c_TYPE(8)  BIRNET_SIG_ARG_c_TYPE(9)  BIRNET_SIG_ARG_c_TYPE(10)  BIRNET_SIG_ARG_c_TYPE(11)  BIRNET_SIG_ARG_c_TYPE(12)  BIRNET_SIG_ARG_c_TYPE(13)  BIRNET_SIG_ARG_c_TYPE(14)
#define BIRNET_SIG_TYPES  BIRNET_SIG_ARG_TYPE(1) , BIRNET_SIG_ARG_TYPE(2) , BIRNET_SIG_ARG_TYPE(3) , BIRNET_SIG_ARG_TYPE(4) , BIRNET_SIG_ARG_TYPE(5) , BIRNET_SIG_ARG_TYPE(6) , BIRNET_SIG_ARG_TYPE(7) , BIRNET_SIG_ARG_TYPE(8) , BIRNET_SIG_ARG_TYPE(9) , BIRNET_SIG_ARG_TYPE(10) , BIRNET_SIG_ARG_TYPE(11) , BIRNET_SIG_ARG_TYPE(12) , BIRNET_SIG_ARG_TYPE(13) , BIRNET_SIG_ARG_TYPE(14)
#define BIRNET_SIG_c_VARS  BIRNET_SIG_ARG_c_VAR(1)  BIRNET_SIG_ARG_c_VAR(2)  BIRNET_SIG_ARG_c_VAR(3)  BIRNET_SIG_ARG_c_VAR(4)  BIRNET_SIG_ARG_c_VAR(5)  BIRNET_SIG_ARG_c_VAR(6)  BIRNET_SIG_ARG_c_VAR(7)  BIRNET_SIG_ARG_c_VAR(8)  BIRNET_SIG_ARG_c_VAR(9)  BIRNET_SIG_ARG_c_VAR(10)  BIRNET_SIG_ARG_c_VAR(11)  BIRNET_SIG_ARG_c_VAR(12)  BIRNET_SIG_ARG_c_VAR(13)  BIRNET_SIG_ARG_c_VAR(14)
#define BIRNET_SIG_VARS  BIRNET_SIG_ARG_VAR(1) , BIRNET_SIG_ARG_VAR(2) , BIRNET_SIG_ARG_VAR(3) , BIRNET_SIG_ARG_VAR(4) , BIRNET_SIG_ARG_VAR(5) , BIRNET_SIG_ARG_VAR(6) , BIRNET_SIG_ARG_VAR(7) , BIRNET_SIG_ARG_VAR(8) , BIRNET_SIG_ARG_VAR(9) , BIRNET_SIG_ARG_VAR(10) , BIRNET_SIG_ARG_VAR(11) , BIRNET_SIG_ARG_VAR(12) , BIRNET_SIG_ARG_VAR(13) , BIRNET_SIG_ARG_VAR(14)
#define BIRNET_SIG_c_TYPED_VARS  BIRNET_SIG_ARG_c_TYPED_VAR(1)  BIRNET_SIG_ARG_c_TYPED_VAR(2)  BIRNET_SIG_ARG_c_TYPED_VAR(3)  BIRNET_SIG_ARG_c_TYPED_VAR(4)  BIRNET_SIG_ARG_c_TYPED_VAR(5)  BIRNET_SIG_ARG_c_TYPED_VAR(6)  BIRNET_SIG_ARG_c_TYPED_VAR(7)  BIRNET_SIG_ARG_c_TYPED_VAR(8)  BIRNET_SIG_ARG_c_TYPED_VAR(9)  BIRNET_SIG_ARG_c_TYPED_VAR(10)  BIRNET_SIG_ARG_c_TYPED_VAR(11)  BIRNET_SIG_ARG_c_TYPED_VAR(12)  BIRNET_SIG_ARG_c_TYPED_VAR(13)  BIRNET_SIG_ARG_c_TYPED_VAR(14)
#define BIRNET_SIG_TYPED_VARS  BIRNET_SIG_ARG_TYPED_VAR(1) , BIRNET_SIG_ARG_TYPED_VAR(2) , BIRNET_SIG_ARG_TYPED_VAR(3) , BIRNET_SIG_ARG_TYPED_VAR(4) , BIRNET_SIG_ARG_TYPED_VAR(5) , BIRNET_SIG_ARG_TYPED_VAR(6) , BIRNET_SIG_ARG_TYPED_VAR(7) , BIRNET_SIG_ARG_TYPED_VAR(8) , BIRNET_SIG_ARG_TYPED_VAR(9) , BIRNET_SIG_ARG_TYPED_VAR(10) , BIRNET_SIG_ARG_TYPED_VAR(11) , BIRNET_SIG_ARG_TYPED_VAR(12) , BIRNET_SIG_ARG_TYPED_VAR(13) , BIRNET_SIG_ARG_TYPED_VAR(14)
#include <rapicorn/birnetsignaldefs.hh>
#undef BIRNET_SIG_c_TYPENAMES
#undef BIRNET_SIG_TYPENAMES
#undef BIRNET_SIG_c_TYPES
#undef BIRNET_SIG_TYPES
#undef BIRNET_SIG_c_VARS
#undef BIRNET_SIG_VARS
#undef BIRNET_SIG_c_TYPED_VARS
#undef BIRNET_SIG_TYPED_VARS
#endif // 14
#if   BIRNET_SIG_MATCH (15)
#undef BIRNET_SIG_NAME
#define BIRNET_SIG_NAME(x) x##15
#define BIRNET_SIG_c_TYPENAMES  BIRNET_SIG_ARG_c_TYPENAME(1)  BIRNET_SIG_ARG_c_TYPENAME(2)  BIRNET_SIG_ARG_c_TYPENAME(3)  BIRNET_SIG_ARG_c_TYPENAME(4)  BIRNET_SIG_ARG_c_TYPENAME(5)  BIRNET_SIG_ARG_c_TYPENAME(6)  BIRNET_SIG_ARG_c_TYPENAME(7)  BIRNET_SIG_ARG_c_TYPENAME(8)  BIRNET_SIG_ARG_c_TYPENAME(9)  BIRNET_SIG_ARG_c_TYPENAME(10)  BIRNET_SIG_ARG_c_TYPENAME(11)  BIRNET_SIG_ARG_c_TYPENAME(12)  BIRNET_SIG_ARG_c_TYPENAME(13)  BIRNET_SIG_ARG_c_TYPENAME(14)  BIRNET_SIG_ARG_c_TYPENAME(15)
#define BIRNET_SIG_TYPENAMES  BIRNET_SIG_ARG_TYPENAME(1) , BIRNET_SIG_ARG_TYPENAME(2) , BIRNET_SIG_ARG_TYPENAME(3) , BIRNET_SIG_ARG_TYPENAME(4) , BIRNET_SIG_ARG_TYPENAME(5) , BIRNET_SIG_ARG_TYPENAME(6) , BIRNET_SIG_ARG_TYPENAME(7) , BIRNET_SIG_ARG_TYPENAME(8) , BIRNET_SIG_ARG_TYPENAME(9) , BIRNET_SIG_ARG_TYPENAME(10) , BIRNET_SIG_ARG_TYPENAME(11) , BIRNET_SIG_ARG_TYPENAME(12) , BIRNET_SIG_ARG_TYPENAME(13) , BIRNET_SIG_ARG_TYPENAME(14) , BIRNET_SIG_ARG_TYPENAME(15)
#define BIRNET_SIG_c_TYPES  BIRNET_SIG_ARG_c_TYPE(1)  BIRNET_SIG_ARG_c_TYPE(2)  BIRNET_SIG_ARG_c_TYPE(3)  BIRNET_SIG_ARG_c_TYPE(4)  BIRNET_SIG_ARG_c_TYPE(5)  BIRNET_SIG_ARG_c_TYPE(6)  BIRNET_SIG_ARG_c_TYPE(7)  BIRNET_SIG_ARG_c_TYPE(8)  BIRNET_SIG_ARG_c_TYPE(9)  BIRNET_SIG_ARG_c_TYPE(10)  BIRNET_SIG_ARG_c_TYPE(11)  BIRNET_SIG_ARG_c_TYPE(12)  BIRNET_SIG_ARG_c_TYPE(13)  BIRNET_SIG_ARG_c_TYPE(14)  BIRNET_SIG_ARG_c_TYPE(15)
#define BIRNET_SIG_TYPES  BIRNET_SIG_ARG_TYPE(1) , BIRNET_SIG_ARG_TYPE(2) , BIRNET_SIG_ARG_TYPE(3) , BIRNET_SIG_ARG_TYPE(4) , BIRNET_SIG_ARG_TYPE(5) , BIRNET_SIG_ARG_TYPE(6) , BIRNET_SIG_ARG_TYPE(7) , BIRNET_SIG_ARG_TYPE(8) , BIRNET_SIG_ARG_TYPE(9) , BIRNET_SIG_ARG_TYPE(10) , BIRNET_SIG_ARG_TYPE(11) , BIRNET_SIG_ARG_TYPE(12) , BIRNET_SIG_ARG_TYPE(13) , BIRNET_SIG_ARG_TYPE(14) , BIRNET_SIG_ARG_TYPE(15)
#define BIRNET_SIG_c_VARS  BIRNET_SIG_ARG_c_VAR(1)  BIRNET_SIG_ARG_c_VAR(2)  BIRNET_SIG_ARG_c_VAR(3)  BIRNET_SIG_ARG_c_VAR(4)  BIRNET_SIG_ARG_c_VAR(5)  BIRNET_SIG_ARG_c_VAR(6)  BIRNET_SIG_ARG_c_VAR(7)  BIRNET_SIG_ARG_c_VAR(8)  BIRNET_SIG_ARG_c_VAR(9)  BIRNET_SIG_ARG_c_VAR(10)  BIRNET_SIG_ARG_c_VAR(11)  BIRNET_SIG_ARG_c_VAR(12)  BIRNET_SIG_ARG_c_VAR(13)  BIRNET_SIG_ARG_c_VAR(14)  BIRNET_SIG_ARG_c_VAR(15)
#define BIRNET_SIG_VARS  BIRNET_SIG_ARG_VAR(1) , BIRNET_SIG_ARG_VAR(2) , BIRNET_SIG_ARG_VAR(3) , BIRNET_SIG_ARG_VAR(4) , BIRNET_SIG_ARG_VAR(5) , BIRNET_SIG_ARG_VAR(6) , BIRNET_SIG_ARG_VAR(7) , BIRNET_SIG_ARG_VAR(8) , BIRNET_SIG_ARG_VAR(9) , BIRNET_SIG_ARG_VAR(10) , BIRNET_SIG_ARG_VAR(11) , BIRNET_SIG_ARG_VAR(12) , BIRNET_SIG_ARG_VAR(13) , BIRNET_SIG_ARG_VAR(14) , BIRNET_SIG_ARG_VAR(15)
#define BIRNET_SIG_c_TYPED_VARS  BIRNET_SIG_ARG_c_TYPED_VAR(1)  BIRNET_SIG_ARG_c_TYPED_VAR(2)  BIRNET_SIG_ARG_c_TYPED_VAR(3)  BIRNET_SIG_ARG_c_TYPED_VAR(4)  BIRNET_SIG_ARG_c_TYPED_VAR(5)  BIRNET_SIG_ARG_c_TYPED_VAR(6)  BIRNET_SIG_ARG_c_TYPED_VAR(7)  BIRNET_SIG_ARG_c_TYPED_VAR(8)  BIRNET_SIG_ARG_c_TYPED_VAR(9)  BIRNET_SIG_ARG_c_TYPED_VAR(10)  BIRNET_SIG_ARG_c_TYPED_VAR(11)  BIRNET_SIG_ARG_c_TYPED_VAR(12)  BIRNET_SIG_ARG_c_TYPED_VAR(13)  BIRNET_SIG_ARG_c_TYPED_VAR(14)  BIRNET_SIG_ARG_c_TYPED_VAR(15)
#define BIRNET_SIG_TYPED_VARS  BIRNET_SIG_ARG_TYPED_VAR(1) , BIRNET_SIG_ARG_TYPED_VAR(2) , BIRNET_SIG_ARG_TYPED_VAR(3) , BIRNET_SIG_ARG_TYPED_VAR(4) , BIRNET_SIG_ARG_TYPED_VAR(5) , BIRNET_SIG_ARG_TYPED_VAR(6) , BIRNET_SIG_ARG_TYPED_VAR(7) , BIRNET_SIG_ARG_TYPED_VAR(8) , BIRNET_SIG_ARG_TYPED_VAR(9) , BIRNET_SIG_ARG_TYPED_VAR(10) , BIRNET_SIG_ARG_TYPED_VAR(11) , BIRNET_SIG_ARG_TYPED_VAR(12) , BIRNET_SIG_ARG_TYPED_VAR(13) , BIRNET_SIG_ARG_TYPED_VAR(14) , BIRNET_SIG_ARG_TYPED_VAR(15)
#include <rapicorn/birnetsignaldefs.hh>
#undef BIRNET_SIG_c_TYPENAMES
#undef BIRNET_SIG_TYPENAMES
#undef BIRNET_SIG_c_TYPES
#undef BIRNET_SIG_TYPES
#undef BIRNET_SIG_c_VARS
#undef BIRNET_SIG_VARS
#undef BIRNET_SIG_c_TYPED_VARS
#undef BIRNET_SIG_TYPED_VARS
#endif // 15
#if   BIRNET_SIG_MATCH (16)
#undef BIRNET_SIG_NAME
#define BIRNET_SIG_NAME(x) x##16
#define BIRNET_SIG_c_TYPENAMES  BIRNET_SIG_ARG_c_TYPENAME(1)  BIRNET_SIG_ARG_c_TYPENAME(2)  BIRNET_SIG_ARG_c_TYPENAME(3)  BIRNET_SIG_ARG_c_TYPENAME(4)  BIRNET_SIG_ARG_c_TYPENAME(5)  BIRNET_SIG_ARG_c_TYPENAME(6)  BIRNET_SIG_ARG_c_TYPENAME(7)  BIRNET_SIG_ARG_c_TYPENAME(8)  BIRNET_SIG_ARG_c_TYPENAME(9)  BIRNET_SIG_ARG_c_TYPENAME(10)  BIRNET_SIG_ARG_c_TYPENAME(11)  BIRNET_SIG_ARG_c_TYPENAME(12)  BIRNET_SIG_ARG_c_TYPENAME(13)  BIRNET_SIG_ARG_c_TYPENAME(14)  BIRNET_SIG_ARG_c_TYPENAME(15)  BIRNET_SIG_ARG_c_TYPENAME(16)
#define BIRNET_SIG_TYPENAMES  BIRNET_SIG_ARG_TYPENAME(1) , BIRNET_SIG_ARG_TYPENAME(2) , BIRNET_SIG_ARG_TYPENAME(3) , BIRNET_SIG_ARG_TYPENAME(4) , BIRNET_SIG_ARG_TYPENAME(5) , BIRNET_SIG_ARG_TYPENAME(6) , BIRNET_SIG_ARG_TYPENAME(7) , BIRNET_SIG_ARG_TYPENAME(8) , BIRNET_SIG_ARG_TYPENAME(9) , BIRNET_SIG_ARG_TYPENAME(10) , BIRNET_SIG_ARG_TYPENAME(11) , BIRNET_SIG_ARG_TYPENAME(12) , BIRNET_SIG_ARG_TYPENAME(13) , BIRNET_SIG_ARG_TYPENAME(14) , BIRNET_SIG_ARG_TYPENAME(15) , BIRNET_SIG_ARG_TYPENAME(16)
#define BIRNET_SIG_c_TYPES  BIRNET_SIG_ARG_c_TYPE(1)  BIRNET_SIG_ARG_c_TYPE(2)  BIRNET_SIG_ARG_c_TYPE(3)  BIRNET_SIG_ARG_c_TYPE(4)  BIRNET_SIG_ARG_c_TYPE(5)  BIRNET_SIG_ARG_c_TYPE(6)  BIRNET_SIG_ARG_c_TYPE(7)  BIRNET_SIG_ARG_c_TYPE(8)  BIRNET_SIG_ARG_c_TYPE(9)  BIRNET_SIG_ARG_c_TYPE(10)  BIRNET_SIG_ARG_c_TYPE(11)  BIRNET_SIG_ARG_c_TYPE(12)  BIRNET_SIG_ARG_c_TYPE(13)  BIRNET_SIG_ARG_c_TYPE(14)  BIRNET_SIG_ARG_c_TYPE(15)  BIRNET_SIG_ARG_c_TYPE(16)
#define BIRNET_SIG_TYPES  BIRNET_SIG_ARG_TYPE(1) , BIRNET_SIG_ARG_TYPE(2) , BIRNET_SIG_ARG_TYPE(3) , BIRNET_SIG_ARG_TYPE(4) , BIRNET_SIG_ARG_TYPE(5) , BIRNET_SIG_ARG_TYPE(6) , BIRNET_SIG_ARG_TYPE(7) , BIRNET_SIG_ARG_TYPE(8) , BIRNET_SIG_ARG_TYPE(9) , BIRNET_SIG_ARG_TYPE(10) , BIRNET_SIG_ARG_TYPE(11) , BIRNET_SIG_ARG_TYPE(12) , BIRNET_SIG_ARG_TYPE(13) , BIRNET_SIG_ARG_TYPE(14) , BIRNET_SIG_ARG_TYPE(15) , BIRNET_SIG_ARG_TYPE(16)
#define BIRNET_SIG_c_VARS  BIRNET_SIG_ARG_c_VAR(1)  BIRNET_SIG_ARG_c_VAR(2)  BIRNET_SIG_ARG_c_VAR(3)  BIRNET_SIG_ARG_c_VAR(4)  BIRNET_SIG_ARG_c_VAR(5)  BIRNET_SIG_ARG_c_VAR(6)  BIRNET_SIG_ARG_c_VAR(7)  BIRNET_SIG_ARG_c_VAR(8)  BIRNET_SIG_ARG_c_VAR(9)  BIRNET_SIG_ARG_c_VAR(10)  BIRNET_SIG_ARG_c_VAR(11)  BIRNET_SIG_ARG_c_VAR(12)  BIRNET_SIG_ARG_c_VAR(13)  BIRNET_SIG_ARG_c_VAR(14)  BIRNET_SIG_ARG_c_VAR(15)  BIRNET_SIG_ARG_c_VAR(16)
#define BIRNET_SIG_VARS  BIRNET_SIG_ARG_VAR(1) , BIRNET_SIG_ARG_VAR(2) , BIRNET_SIG_ARG_VAR(3) , BIRNET_SIG_ARG_VAR(4) , BIRNET_SIG_ARG_VAR(5) , BIRNET_SIG_ARG_VAR(6) , BIRNET_SIG_ARG_VAR(7) , BIRNET_SIG_ARG_VAR(8) , BIRNET_SIG_ARG_VAR(9) , BIRNET_SIG_ARG_VAR(10) , BIRNET_SIG_ARG_VAR(11) , BIRNET_SIG_ARG_VAR(12) , BIRNET_SIG_ARG_VAR(13) , BIRNET_SIG_ARG_VAR(14) , BIRNET_SIG_ARG_VAR(15) , BIRNET_SIG_ARG_VAR(16)
#define BIRNET_SIG_c_TYPED_VARS  BIRNET_SIG_ARG_c_TYPED_VAR(1)  BIRNET_SIG_ARG_c_TYPED_VAR(2)  BIRNET_SIG_ARG_c_TYPED_VAR(3)  BIRNET_SIG_ARG_c_TYPED_VAR(4)  BIRNET_SIG_ARG_c_TYPED_VAR(5)  BIRNET_SIG_ARG_c_TYPED_VAR(6)  BIRNET_SIG_ARG_c_TYPED_VAR(7)  BIRNET_SIG_ARG_c_TYPED_VAR(8)  BIRNET_SIG_ARG_c_TYPED_VAR(9)  BIRNET_SIG_ARG_c_TYPED_VAR(10)  BIRNET_SIG_ARG_c_TYPED_VAR(11)  BIRNET_SIG_ARG_c_TYPED_VAR(12)  BIRNET_SIG_ARG_c_TYPED_VAR(13)  BIRNET_SIG_ARG_c_TYPED_VAR(14)  BIRNET_SIG_ARG_c_TYPED_VAR(15)  BIRNET_SIG_ARG_c_TYPED_VAR(16)
#define BIRNET_SIG_TYPED_VARS  BIRNET_SIG_ARG_TYPED_VAR(1) , BIRNET_SIG_ARG_TYPED_VAR(2) , BIRNET_SIG_ARG_TYPED_VAR(3) , BIRNET_SIG_ARG_TYPED_VAR(4) , BIRNET_SIG_ARG_TYPED_VAR(5) , BIRNET_SIG_ARG_TYPED_VAR(6) , BIRNET_SIG_ARG_TYPED_VAR(7) , BIRNET_SIG_ARG_TYPED_VAR(8) , BIRNET_SIG_ARG_TYPED_VAR(9) , BIRNET_SIG_ARG_TYPED_VAR(10) , BIRNET_SIG_ARG_TYPED_VAR(11) , BIRNET_SIG_ARG_TYPED_VAR(12) , BIRNET_SIG_ARG_TYPED_VAR(13) , BIRNET_SIG_ARG_TYPED_VAR(14) , BIRNET_SIG_ARG_TYPED_VAR(15) , BIRNET_SIG_ARG_TYPED_VAR(16)
#include <rapicorn/birnetsignaldefs.hh>
#undef BIRNET_SIG_c_TYPENAMES
#undef BIRNET_SIG_TYPENAMES
#undef BIRNET_SIG_c_TYPES
#undef BIRNET_SIG_TYPES
#undef BIRNET_SIG_c_VARS
#undef BIRNET_SIG_VARS
#undef BIRNET_SIG_c_TYPED_VARS
#undef BIRNET_SIG_TYPED_VARS
#endif // 16

/* --- generated contents end --- */

#undef BIRNET_SIGNAL_CODE_GENERATION

#undef BIRNET_SIG_MATCH
#undef BIRNET_SIG_NAME
/* undef all arg repetitions */
#undef BIRNET_SIG_c_TYPENAMES
#undef BIRNET_SIG_TYPENAMES
#undef BIRNET_SIG_c_TYPES
#undef BIRNET_SIG_TYPES
#undef BIRNET_SIG_c_VARS
#undef BIRNET_SIG_VARS
#undef BIRNET_SIG_c_TYPED_VARS
#undef BIRNET_SIG_TYPED_VARS
