# Rules to build documentation via Doxygen		-*-mode:makefile;-*-

DOXYGEN_PROJECT_NUMBER = ${VERSION}

DOCU_GLOBS  = *.dox *.py $(DOCU_HGLOBS)
DOCU_HGLOBS = *.idl *.h *.H *.hh *.proc
DOCU_CGLOBS = $(DOCU_GLOBS) *.c *.C *.cc
DOXYGEN_SRCTREE     = doxygen-srctree
DOXYGENV    = doxygen-1.7.4
DOXYGEN     = $(if $(shell which $(DOXYGENV)), $(DOXYGENV), doxygen)
GPRINT	    = @printf '  %-7s%s\n'
Q           = $(if $(findstring 1, $(V)) ,, @)

CHANGELOG_SED = -e 's/(@\w)/\\\1/g; s/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s,\*/,*\&nbps;/,g' \
		-e '/^[^ ].*\# [0-9a-f]/s/^(.*)\# ([0-9a-f]+)/@section commit_\2 \0/' \
		-e 's/^[ \t]+\*? ?([a-zA-Z0-9_.+\/-]+):[ \t]*(\w.*)$$/- @b \1: \2/' \
		-e 's/^[ \t]+\*? ?([a-zA-Z0-9_.+\/-]+):(.*)/- <em><b>\1:<\/b> \2<\/em>/' \
		-e 's/^/ * /'

.PHONY: $(DOXYGEN_SRCTREE)
$(DOXYGEN_SRCTREE):
	$(GPRINT) "GEN" $(DOXYGEN_SRCTREE)/
	$(Q) rm -rf $(DOXYGEN_SRCTREE)/ && mkdir -p $(DOXYGEN_SRCTREE)/
	$(GPRINT) "GEN" "ChangeLog"
	$(Q) test -f $(top_srcdir)/ChangeLog || { echo "Missing $(top_srcdir)/ChangeLog" >&2 ; false ; }
	$(Q) echo '/*! @page ChangeLog' $(DOXYGEN_CHANGELOG_TITLE)	 > $(DOXYGEN_SRCTREE)/ChangeLog
	$(Q) sed -r $(CHANGELOG_SED) <$(top_srcdir)/ChangeLog	>> $(DOXYGEN_SRCTREE)/ChangeLog
	$(Q) echo ' */' 					>> $(DOXYGEN_SRCTREE)/ChangeLog
	$(GPRINT) "COPY" "Source tree..." \
	&& CWD=`pwd` \
	&& for dir in $(DOXYGEN_DOC_DIRS) ; do \
	  (mkdir -p $$CWD/$(DOXYGEN_SRCTREE)/$$dir/ \
	   && cd $(top_srcdir)/$$dir \
	   && find . -maxdepth 1 -type f \( $(patsubst %,-name '%' -o, $(DOCU_CGLOBS)) -false \) \
	      -exec cp {} $$CWD/$(DOXYGEN_SRCTREE)/$$dir/{} \; ) || exit $? ; \
	  done \
	$(foreach FILE, $(DOXYGEN_DOC_FILES), \
	  && cp $(top_srcdir)/$(FILE) $(DOXYGEN_SRCTREE)/$(dir $(FILE)))
	$(GPRINT) "ADD" "File docu commands..." \
	&& cd $(DOXYGEN_SRCTREE)/ \
	&& find . -type f \( $(patsubst %,-name '%' -o, $(DOCU_GLOBS)) -false \) \
	   -exec sed  '1,+0s,^,/** @file {} */,' {} --in-place \;
	$(GPRINT) "PRUNE" "Exclude files..." \
	&& rm -f $(patsubst %, $(DOXYGEN_SRCTREE)/%, $(DOXYGEN_EXCLUDES))

DOXYGEN_SED_ACCESSKEY_AS_F = -e 's/(<input [^>]*id="MSearchField"[^>]*accesskey=")S"/\1F"/'

doxygen-html: doxygen.cfg tagfile-susv4.xml tagfile-unix.xml
	$(GPRINT) "TIDY" "Temporaries..."
	$(Q) rm -rf doxygen-html.tmp/ && mkdir -p doxygen-html.tmp/
	$(Q) $(MAKE) $(DOXYGEN_SRCTREE)
	$(GPRINT) "GEN" "HTML Documentation..."
	$(Q) (cat doxygen.cfg \
	&& echo "STRIP_FROM_PATH  = `pwd`/$(DOXYGEN_SRCTREE)" \
	&& echo "INPUT		  = $(DOXYGEN_SRCTREE)/" \
	&& echo "EXAMPLE_PATH	  = $(DOXYGEN_SRCTREE)/" \
	&& echo "OUTPUT_DIRECTORY = doxygen-html.tmp/" \
	&& echo "GENERATE_TAGFILE = doxygen-html.tmp/html/tagfile.xml" \
	&& echo "TAGFILES         = tagfile-susv4.xml=http://pubs.opengroup.org/onlinepubs/9699919799/ \\" \
	&& echo "                   tagfile-unix.xml=http://www.unix.org/" \
	&& echo -n "PROJECT_NUMBER = $(DOXYGEN_PROJECT_NUMBER)" \
	) | nice $(DOXYGEN) - > error.log 2>&1
	$(Q) test ! -s error.log && rm -f error.log \
	|| { echo "WARNING: doxygen issues encountered ($$(wc -l <error.log)): $$(pwd)/error.log" ; cat error.log $(Q:@=1>/dev/null) ; }
	$(GPRINT) "POLISH" "HTML Files..."
	$(Q) sed -r $(DOXYGEN_SED_ACCESSKEY_AS_F) -i doxygen-html.tmp/html/*.html
	$(GPRINT) "MOVE" "doxygen-html/..."
	$(Q) rm -rf doxygen-html/ && mv doxygen-html.tmp/html/ doxygen-html/
	$(GPRINT) "CLEAN" "Temporaries..."
	$(Q) rm -rf $(DOXYGEN_SRCTREE)/ doxygen-html.tmp/
.PHONY: doxygen-html

clean-local: doxygen-clean

doxygen-clean:
	rm -rf $(DOXYGEN_SRCTREE)/ doxygen-html.tmp/ doxygen-html/
	rm -rf error.log
.PHONY: doxygen-clean
