.TH "PLIC" "1" "2007-09-27" "plic-0.3" "Plic Manual Pages"

.SH
NAME
.PP
plic - Pluggable IDL Compiler

.SH
SYNOPSIS
.PP
\fBplic.py\fP [\fIOPTIONS\fP] [\fIIDL-FILES...\fP]

.SH
DESCRIPTION
.PP
The \fBplic\fP IDL compiler is used to parse conscise programming interface
definitions and generate various kinds of code or documentation from it.

