
namespace AidaTests {

  typedef string SimpleString;

  typedef int IntWithFooAsLabel = Int ("Foo");

  typedef float FloatWithBlurbBlurb = Float ("Float Label", "Float Blurb", "rw", 97.97);

  typedef int IntAuxRange = Range ("Int Range", "This int demonstrates range data use", "rw:extra-option", -100, +100, -5);
  typedef float FloatAuxRange = Range ("Float Range", "This float demonstrates range data use", "rw:extra-option", -100, +100, -5);
  typedef string ExtendedString = String ("Extended String", "Demonstrate full string specification", "ro", "Default-String-Value");

  enum EnumType { ENUM_VALUE0, ENUM_VALUE1 };

  typedef EnumType Enum1;

  sequence SimpleSequence {
    int sample_integer;
  };

  record SimpleRecord {
    int    intfield;
    float  floatfield;
    string stringfield;
    any    anyfield;
  };

}
