// Licensed GNU LGPL v3 or later: http://www.gnu.org/licenses/lgpl.html -*-mode:c++;-*-

namespace Rapicorn {

/**
 * Helper class, part of the IDL interface but implemented by rapicorn-core.
 */
interface BaseObject {};

} // Rapicorn
