
namespace RapicornTest {

  typedef string SimpleString;

  typedef int IntWithFooAsLabel = Int ("Foo");

  typedef float FloatWithBlurbBlurb = Float ("Float Label", "Float Blurb", 97.97);

  typedef int ExtendIntWithAux = Int ("Extended int", "This int demonstrates extensive auxillary data use",
				      33, -100, +100, -5, "rw:extra-option");
  typedef string ExtendedString = String ("Extended String", "Demonstrate full string specification",
					  "Default-String-Value", "ro");
  enum EnumType { ENUM_VALUE0, ENUM_VALUE1 };

  typedef EnumType Enum1;

  record SimpleRecord {
    int sample_integer;
  };

  sequence SimpleSequence {
    int sample_integer;
  };

}
